version: "3.9"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  cache:
    image: redis
    restart: always
    ports:
      - 6379:6379

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.dev
    depends_on:
      - db
    ports:
      - 8080:8080
    restart: always
    env_file: backend.env
    environment:
      APP_URL: ${APP_URL}
      APP_ENV: ${APP_ENV}
      DATABASE_URL: ${DATABASE_URL}
      CACHE_URL: ${CACHE_URL}