version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    ports:
      - 3000:3000
    restart: always
    env_file: frontend.env
    environment:
      API_URL: ${API_URL}
