FROM golang:1.19

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY *.go ./
COPY domains/ ./domains
COPY migrations/ ./migrations
COPY scripts/ ./scripts
COPY shared/ ./shared

RUN CGO_ENABLED=0 GOOS=linux go build -o /backend

CMD ["/backend"]